# Generated by Django 3.2.4 on 2021-06-18 16:40

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=150, message='You probably need more than that to elaborate yout thought!')])),
                ('slug', models.SlugField(max_length=16)),
                ('posted', models.BooleanField(default=False)),
                ('date_created', models.DateField(default=datetime.date(2021, 6, 18))),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
