# Generated by Django 3.2.4 on 2021-06-20 05:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210619_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 6, 20)),
        ),
    ]
