# Generated by Django 3.2.4 on 2021-06-27 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_postmodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 6, 27)),
        ),
    ]
