# Generated by Django 3.2.4 on 2021-07-10 06:00

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_alter_postmodel_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityonlypost',
            name='is_restricted',
        ),
        migrations.AddField(
            model_name='communityonlypost',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 7, 10)),
        ),
        migrations.AddField(
            model_name='communityonlypost',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communityonlypost',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communityonlypost',
            name='slug',
            field=models.SlugField(blank=True, max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='communityonlypost',
            name='userdata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communityonlypost',
            name='post',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=300, message='You probably need more characters!')]),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='date_created',
            field=models.DateField(default=datetime.date(2021, 7, 10)),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='post',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(limit_value=300, message='You probably need more characters')]),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
