# Generated by Django 3.2.4 on 2021-07-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210710_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='posted',
            field=models.BooleanField(default=True),
        ),
    ]
