# Generated by Django 3.2.4 on 2021-07-10 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_postmodel_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 7, 10, 12, 20, 47, 888856, tzinfo=utc)),
        ),
    ]
