# Generated by Django 3.2.4 on 2021-07-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_postmodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
