# Generated by Django 3.2.4 on 2021-07-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_postmodel_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
