# Generated by Django 3.2.4 on 2021-07-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_postmodel_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityonlypost',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='communityonlypost',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
