# Generated by Django 3.2.4 on 2021-07-13 07:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20210711_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='referred',
        ),
        migrations.AlterField(
            model_name='communityonlypost',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 7, 33, 14, 582327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 7, 33, 14, 579329, tzinfo=utc)),
        ),
    ]
