# Generated by Django 3.2.4 on 2021-06-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiumuser',
            old_name='username',
            new_name='userdata',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='userdata',
        ),
    ]
