# Generated by Django 3.2.4 on 2021-06-19 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210618_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_name', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('userdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MembersRoomResident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('membership_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.membersroom')),
            ],
        ),
    ]
